/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practice;

/**
 *
 * @author Noojar
 */
public class Tree_Gui extends javax.swing.JFrame {

    Node A = new Node();
    Node B = new Node();
    Node C = new Node();
    Node D = new Node();
    Node E = new Node();
    Node F = new Node();
    Node G = new Node();
    Node H = new Node();
    Node J = new Node();
    Node K = new Node();
    Node L = new Node();

    Node ROOT;  //กำหนดตัวแปร ROOT
    Node PTR;
    Node STACT[] = new Node[10];
    int TOP;
    /**
     * Creates new form Tree_Gui
     */
    public Tree_Gui() {
        A.INFOR = "A";
        B.INFOR = "B";
        C.INFOR = "C";
        D.INFOR = "D";
        E.INFOR = "E";
        F.INFOR = "F";
        G.INFOR = "G";
        H.INFOR = "H";
        J.INFOR = "J";
        K.INFOR = "K";
        L.INFOR = "L";
        //เชื่อมโยงการใช้งานตามรูปภาพที่ 7-6
        A.LEFT = B;
        A.RIGHT = C;
        B.LEFT = D;
        B.RIGHT = E;
        E.LEFT = F;
        C.LEFT = G;
        C.RIGHT = H;
        H.LEFT = J;
        H.RIGHT = K;
        J.LEFT = L;
        ROOT = A;  // กำหนดค่า Root ชี้ไปยังโนด A
        initComponents();

    }

    public void PREORDER(Node root) {
        int TOP = 1;
        STACT[1] = null;
        Node PTR = root;
        jTextArea1.setText("");
        while (PTR != null) {
            System.out.println(PTR.INFOR); //Apply PROCESS to INFOR[PTR]
            jTextArea1.setText(jTextArea1.getText()+"\n"+PTR.INFOR);
            if (PTR.RIGHT != null) {
                TOP++;
                STACT[TOP] = PTR.RIGHT;
            }
            if (PTR.LEFT != null) {
                PTR = PTR.LEFT;
            } else {
                PTR = STACT[TOP];
                TOP--;
            }
        }//end of while loop
    }
    public void PreOderRecursive(Node root) {
    if(root != null ){
            System.out.println(root.INFOR); //Apply PROCESS to INFOR[PTR]
            jTextArea1.setText(jTextArea1.getText()+"\n"+root.INFOR);
            PreOderRecursive(root.LEFT);
            PreOderRecursive(root.RIGHT);
    
    }
    
    
    }
    public void INORDER(Node root){
    PTR=root;
    Step2();    
    PTR = STACT[TOP]; TOP--; 
    jTextArea1.setText("");
    while(PTR != null){           //step 4
      System.out.println(PTR.INFOR); //step5
      jTextArea1.setText(jTextArea1.getText()+"\n"+PTR.INFOR);
      if(PTR.RIGHT != null){   //step 6
          PTR = PTR.RIGHT;
          Step2();
      }
        PTR = STACT[TOP]; TOP--;       
    }    
} 
    
     public  void Step2(){
    while(PTR != null){
      TOP++;  STACT[TOP] = PTR;
      PTR = PTR.LEFT;
    }//end of while loop
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Pre-Oder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pre-OderRecursive");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("In-Oder");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PREORDER(ROOT);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreOderRecursive(ROOT);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      INORDER(ROOT);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tree_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tree_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tree_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tree_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tree_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
